### ISSUE TITLE
Android linker issues

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/caveexpress#17]
logcat output

E/AndroidRuntime(14607): FATAL EXCEPTION: SDLThread
E/AndroidRuntime(14607): java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeInit:(Ljava/lang/Object;)I
E/AndroidRuntime(14607): 	at org.libsdl.app.SDLActivity.nativeInit(Native Method)
E/AndroidRuntime(14607): 	at org.libsdl.app.SDLMain.run(SDLActivity.java:936)
E/AndroidRuntime(14607): 	at java.lang.Thread.run(Thread.java:841)

**Comment by mgerhardy** [comment]
mgerhardy@mgerhardy:~/dev/cp-build-android$ /home/mgerhardy/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm ./Debug/lib/libsdl2.a | grep nativeInit
00000000 T Java_org_libsdl_app_SDLActivity_nativeInit

**Comment by mgerhardy** [comment]
mgerhardy@mgerhardy:~/dev/cp-build-android/android-caveexpress$ /home/mgerhardy/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm libs/armeabi/libcaveexpress.so  | grep SDL | grep native
003a6288 T Java_org_libsdl_app_SDLActivity_nativeAddJoystick
003a63e8 T Java_org_libsdl_app_SDLActivity_nativeFlipBuffers
003a66f8 T Java_org_libsdl_app_SDLActivity_nativeGetHint
003a64e4 T Java_org_libsdl_app_SDLActivity_nativeLowMemory
003a654c T Java_org_libsdl_app_SDLActivity_nativePause
003a64fc T Java_org_libsdl_app_SDLActivity_nativeQuit
003a62e0 T Java_org_libsdl_app_SDLActivity_nativeRemoveJoystick
003a65e4 T Java_org_libsdl_app_SDLActivity_nativeResume
003a667c T Java_org_libsdl_app_SDLInputConnection_nativeCommitText
003a66b8 T Java_org_libsdl_app_SDLInputConnection_nativeSetComposingText

**Comment by mgerhardy** [comment]
Linking CXX shared library ../../../android-cavepacker/libs/armeabi/libcavepacker.so
cd src/cavepacker/main && /usr/bin/cmake -E cmake_link_script CMakeFiles/cavepacker.dir/link.txt --verbose=1
/home/mgerhardy/android-ndk-r10d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++  -fPIC -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb --sysroot=/home/mgerhardy/android-ndk-r10d/platforms/android-13/arch-arm -fPIC -fno-strict-aliasing -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security -DGL_GLEXT_PROTOTYPES -std=c++11 -fno-rtti -fno-exceptions -I/home/mgerhardy/android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.8/include -I/home/mgerhardy/android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include -I/home/mgerhardy/android-ndk-r10d/android-13/arch-arm/usr/include -Wall -Wno-multichar -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wno-long-long -Wno-overloaded-virtual -O0 -fno-omit-frame-pointer -g -DDEBUG -shared --sysroot=/home/mgerhardy/android-ndk-r10d/platforms/android-13/arch-arm -L/home/mgerhardy/android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -no-canonical-prefixes -Wl,--fix-cortex-a8 -Wl,--no-warn-mismatch -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -pthread -dead_strip -shared -Wl,-soname,libcavepacker.so -o ../../../android-cavepacker/libs/armeabi/libcavepacker.so CMakeFiles/cavepacker.dir/CavePacker.cpp.o CMakeFiles/cavepacker.dir/__/__/Main.cpp.o ../../../Debug/lib/libcavepacker-server.a ../../../Debug/lib/libcavepacker-client.a ../../../Debug/lib/libcavepacker-shared.a ../../../Debug/lib/libserver.a ../../../Debug/lib/libclient.a ../../../Debug/lib/libgfx.a ../../../Debug/lib/libui.a ../../../Debug/lib/libsprite.a ../../../Debug/lib/libsound.a ../../../Debug/lib/libSDL2_mixer.a -lGLESv1_CM -lGLESv2 ../../../Debug/lib/libparticle.a ../../../Debug/lib/libtexture.a ../../../Debug/lib/libSDL2_image.a ../../../Debug/lib/libservice.a ../../../Debug/lib/libnetwork.a ../../../Debug/lib/libSDL2_net.a ../../../Debug/lib/libgame.a ../../../Debug/lib/libcampaign.a ../../../Debug/lib/libcommon.a ../../../Debug/lib/liblua5.2.a ../../../Debug/lib/libsdl2.a ../../../Debug/lib/libsqlite3.a ../../../Debug/lib/libbox2d.a ../../../Debug/lib/libglm.a ../../../Debug/lib/libzlib.a -ldl -ldl -landroid -llog -lm -lz -lc -lgcc -lgnustl_static
