### ISSUE TITLE
CAVEPACKER: crash in test (ASan)

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/caveexpress#42]
```
[ RUN      ] SokobanMapTest.testsasquatch02_0017
==7052==ERROR: AddressSanitizer failed to allocate 0x200002000 (8589942784) bytes of LargeMmapAllocator: 12
==7052==Process memory map follows:
	0x000000400000-0x000001288000	/home/mgerhardy/dev/caveexpress/tests_cavepacker
	0x000001487000-0x000001489000	/home/mgerhardy/dev/caveexpress/tests_cavepacker
	0x000001489000-0x000001563000	/home/mgerhardy/dev/caveexpress/tests_cavepacker
	0x000001563000-0x00000158a000	
	0x00007fff7000-0x00008fff7000	
	0x00008fff7000-0x02008fff7000	
	0x02008fff7000-0x10007fff8000	
	0x600000000000-0x602000000000	
	0x602000000000-0x602001200000	
	0x602001200000-0x603000000000	
	0x603000000000-0x603003b10000	
	0x603003b10000-0x604000000000	
	0x604000000000-0x6040063e0000	
	0x6040063e0000-0x606000000000	
	0x606000000000-0x606000fa0000	
	0x606000fa0000-0x607000000000	
	0x607000000000-0x6070018d0000	
	0x6070018d0000-0x608000000000	
	0x608000000000-0x6080070c0000	
	0x6080070c0000-0x60b000000000	
	0x60b000000000-0x60b000f00000	
	0x60b000f00000-0x60c000000000	
	0x60c000000000-0x60c000330000	
	0x60c000330000-0x60d000000000	
	0x60d000000000-0x60d001050000	
	0x60d001050000-0x60e000000000	
	0x60e000000000-0x60e000230000	
	0x60e000230000-0x60f000000000	
	0x60f000000000-0x60f000290000	
	0x60f000290000-0x610000000000	
	0x610000000000-0x610000430000	
	0x610000430000-0x611000000000	
	0x611000000000-0x611003840000	
	0x611003840000-0x612000000000	
	0x612000000000-0x612006530000	
	0x612006530000-0x613000000000	
	0x613000000000-0x613003bb0000	
	0x613003bb0000-0x614000000000	
	0x614000000000-0x614005cc0000	
	0x614005cc0000-0x615000000000	
	0x615000000000-0x615006bc0000	
	0x615006bc0000-0x616000000000	
	0x616000000000-0x616006e10000	
	0x616006e10000-0x617000000000	
	0x617000000000-0x617001b70000	
	0x617001b70000-0x618000000000	
	0x618000000000-0x6180017c0000	
	0x6180017c0000-0x619000000000	
	0x619000000000-0x619002820000	
	0x619002820000-0x61a000000000	
	0x61a000000000-0x61a001130000	
	0x61a001130000-0x61b000000000	
	0x61b000000000-0x61b0005a0000	
	0x61b0005a0000-0x61c000000000	
	0x61c000000000-0x61c000b90000	
	0x61c000b90000-0x61d000000000	
	0x61d000000000-0x61d000f30000	
	0x61d000f30000-0x61e000000000	
	0x61e000000000-0x61e000330000	
	0x61e000330000-0x61f000000000	
	0x61f000000000-0x61f001610000	
	0x61f001610000-0x620000000000	
	0x620000000000-0x620000220000	
	0x620000220000-0x621000000000	
	0x621000000000-0x6210007b0000	
	0x6210007b0000-0x622000000000	
	0x622000000000-0x6220001c0000	
	0x6220001c0000-0x623000000000	
	0x623000000000-0x623000030000	
	0x623000030000-0x624000000000	
	0x624000000000-0x624001460000	
	0x624001460000-0x625000000000	
	0x625000000000-0x625001ed0000	
	0x625001ed0000-0x626000000000	
	0x626000000000-0x626000020000	
	0x626000020000-0x627000000000	
	0x627000000000-0x627000070000	
	0x627000070000-0x628000000000	
	0x628000000000-0x628000010000	
	0x628000010000-0x629000000000	
	0x629000000000-0x629000e10000	
	0x629000e10000-0x62b000000000	
	0x62b000000000-0x62b000400000	
	0x62b000400000-0x62c000000000	
	0x62c000000000-0x62c000490000	
	0x62c000490000-0x62d000000000	
	0x62d000000000-0x62d000b40000	
	0x62d000b40000-0x62e000000000	
	0x62e000000000-0x62e000020000	
	0x62e000020000-0x630000000000	
	0x630000000000-0x630002870000	
	0x630002870000-0x631000000000	
	0x631000000000-0x631000090000	
	0x631000090000-0x634000000000	
	0x634000000000-0x634000040000	
	0x634000040000-0x640000000000	
	0x640000000000-0x640000003000	
	0x7f480b19c000-0x7f490b19e000	
	0x7f49cb1a2000-0x7f4a5a0b0000	
	0x7f4ad1b0f000-0x7f4add487000	
	0x7f4add48d000-0x7f4add86f000	
	0x7f4add871000-0x7f4add8c1000	
	0x7f4add8c2000-0x7f4addb18000	
	0x7f4addb18000-0x7f4addb23000	/lib/x86_64-linux-gnu/libnss_files-2.19.so
	0x7f4addb23000-0x7f4addd22000	/lib/x86_64-linux-gnu/libnss_files-2.19.so
	0x7f4addd22000-0x7f4addd23000	/lib/x86_64-linux-gnu/libnss_files-2.19.so
	0x7f4addd23000-0x7f4addd24000	/lib/x86_64-linux-gnu/libnss_files-2.19.so
	0x7f4addd24000-0x7f4addd2f000	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
	0x7f4addd2f000-0x7f4addf2e000	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
	0x7f4addf2e000-0x7f4addf2f000	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
	0x7f4addf2f000-0x7f4addf30000	/lib/x86_64-linux-gnu/libnss_nis-2.19.so
	0x7f4addf30000-0x7f4addf47000	/lib/x86_64-linux-gnu/libnsl-2.19.so
	0x7f4addf47000-0x7f4ade146000	/lib/x86_64-linux-gnu/libnsl-2.19.so
	0x7f4ade146000-0x7f4ade147000	/lib/x86_64-linux-gnu/libnsl-2.19.so
	0x7f4ade147000-0x7f4ade148000	/lib/x86_64-linux-gnu/libnsl-2.19.so
	0x7f4ade148000-0x7f4ade14a000	
	0x7f4ade14a000-0x7f4ade153000	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
	0x7f4ade153000-0x7f4ade352000	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
	0x7f4ade352000-0x7f4ade353000	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
	0x7f4ade353000-0x7f4ade354000	/lib/x86_64-linux-gnu/libnss_compat-2.19.so
	0x7f4ade354000-0x7f4ae065a000	
	0x7f4ae065a000-0x7f4ae0670000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7f4ae0670000-0x7f4ae086f000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7f4ae086f000-0x7f4ae0870000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7f4ae0870000-0x7f4ae0871000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7f4ae0871000-0x7f4ae0a2b000	/lib/x86_64-linux-gnu/libc-2.19.so
	0x7f4ae0a2b000-0x7f4ae0c2a000	/lib/x86_64-linux-gnu/libc-2.19.so
	0x7f4ae0c2a000-0x7f4ae0c2e000	/lib/x86_64-linux-gnu/libc-2.19.so
	0x7f4ae0c2e000-0x7f4ae0c30000	/lib/x86_64-linux-gnu/libc-2.19.so
	0x7f4ae0c30000-0x7f4ae0c35000	
	0x7f4ae0c35000-0x7f4ae0c4e000	/lib/x86_64-linux-gnu/libpthread-2.19.so
	0x7f4ae0c4e000-0x7f4ae0e4d000	/lib/x86_64-linux-gnu/libpthread-2.19.so
	0x7f4ae0e4d000-0x7f4ae0e4e000	/lib/x86_64-linux-gnu/libpthread-2.19.so
	0x7f4ae0e4e000-0x7f4ae0e4f000	/lib/x86_64-linux-gnu/libpthread-2.19.so
	0x7f4ae0e4f000-0x7f4ae0e53000	
	0x7f4ae0e53000-0x7f4ae0f58000	/lib/x86_64-linux-gnu/libm-2.19.so
	0x7f4ae0f58000-0x7f4ae1157000	/lib/x86_64-linux-gnu/libm-2.19.so
	0x7f4ae1157000-0x7f4ae1158000	/lib/x86_64-linux-gnu/libm-2.19.so
	0x7f4ae1158000-0x7f4ae1159000	/lib/x86_64-linux-gnu/libm-2.19.so
	0x7f4ae1159000-0x7f4ae1249000	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
	0x7f4ae1249000-0x7f4ae1449000	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
	0x7f4ae1449000-0x7f4ae1451000	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
	0x7f4ae1451000-0x7f4ae1453000	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20
	0x7f4ae1453000-0x7f4ae1468000	
	0x7f4ae1468000-0x7f4ae146b000	/lib/x86_64-linux-gnu/libdl-2.19.so
	0x7f4ae146b000-0x7f4ae166a000	/lib/x86_64-linux-gnu/libdl-2.19.so
	0x7f4ae166a000-0x7f4ae166b000	/lib/x86_64-linux-gnu/libdl-2.19.so
	0x7f4ae166b000-0x7f4ae166c000	/lib/x86_64-linux-gnu/libdl-2.19.so
	0x7f4ae166c000-0x7f4ae170c000	/usr/lib/x86_64-linux-gnu/libasan.so.1.0.0
	0x7f4ae170c000-0x7f4ae190c000	/usr/lib/x86_64-linux-gnu/libasan.so.1.0.0
	0x7f4ae190c000-0x7f4ae190e000	/usr/lib/x86_64-linux-gnu/libasan.so.1.0.0
	0x7f4ae190e000-0x7f4ae190f000	/usr/lib/x86_64-linux-gnu/libasan.so.1.0.0
	0x7f4ae190f000-0x7f4ae2548000	
	0x7f4ae2548000-0x7f4ae256b000	/lib/x86_64-linux-gnu/ld-2.19.so
	0x7f4ae2576000-0x7f4ae273f000	
	0x7f4ae273f000-0x7f4ae276a000	
	0x7f4ae276a000-0x7f4ae276b000	/lib/x86_64-linux-gnu/ld-2.19.so
	0x7f4ae276b000-0x7f4ae276c000	/lib/x86_64-linux-gnu/ld-2.19.so
	0x7f4ae276c000-0x7f4ae276d000	
	0x7ffc9dc90000-0x7ffc9dcc8000	[stack]
	0x7ffc9ddc1000-0x7ffc9ddc3000	[vdso]
	0x7ffc9ddc3000-0x7ffc9ddc5000	[vvar]
	0xffffffffff600000-0xffffffffff601000	[vsyscall]
==7052==End of process memory map.
==7052==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix.cc:66 "(("unable to mmap" && 0)) != (0)" (0x0, 0x0)
    #0 0x7f4ae16c9050 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x5d050)
    #1 0x7f4ae16cd2b3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x612b3)
    #2 0x7f4ae16d2121 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x66121)
    #3 0x7f4ae1688b28 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x1cb28)
    #4 0x7f4ae16c40d6 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x580d6)
    #5 0x7f4ae121c668 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xc3668)
    #6 0x7f4ae121d30a in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xc430a)
    #7 0x7f4ae121d3bf in std::string::reserve(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xc43bf)
    #8 0x7f4ae121d4b7 in std::string::append(std::string const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xc44b7)
    #9 0x8cc977 in cavepacker::Map::getSolution() const /home/mgerhardy/dev/caveexpress/src/cavepacker/server/map/Map.cpp:134
    #10 0x8d0333 in cavepacker::Map::load(std::string const&) /home/mgerhardy/dev/caveexpress/src/cavepacker/server/map/Map.cpp:537
    #11 0x7e84d0 in cavepacker::SokobanMapTest::testMap(std::string const&, bool) (/home/mgerhardy/dev/caveexpress/tests_cavepacker+0x7e84d0)
    #12 0x7e7ea1 in cavepacker::SokobanMapTest::testSingleMap(std::string const&, bool) /home/mgerhardy/dev/caveexpress/src/cavepacker/tests/SokobanMapTest.cpp:32
    #13 0x7bcba7 in cavepacker::SokobanMapTest_testsasquatch02_0017_Test::TestBody() /home/mgerhardy/dev/caveexpress/src/cavepacker/tests/SokobanMapTest.cpp:823
    #14 0xfceb67 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2063
    #15 0xfc8bf6 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2116
    #16 0xfa7bd6 in testing::Test::Run() /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2136
    #17 0xfa8695 in testing::TestInfo::Run() /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2311
    #18 0xfa8e6d in testing::TestCase::Run() /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2418
    #19 0xfb211d in testing::internal::UnitTestImpl::RunAllTests() /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:4222
    #20 0xfd00ed in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2063
    #21 0xfc9bfa in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:2116
    #22 0xfb0197 in testing::UnitTest::Run() /home/mgerhardy/dev/caveexpress/src/libs/gtest/src/gtest.cc:3835
    #23 0x8a579c in RUN_ALL_TESTS() /home/mgerhardy/dev/caveexpress/src/libs/gtest/include/gtest/gtest.h:2257
    #24 0x8a5509 in main /home/mgerhardy/dev/caveexpress/src/tests/TestAll.cpp:105
    #25 0x7f4ae0892ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #26 0x774678 (/home/mgerhardy/dev/caveexpress/tests_cavepacker+0x774678)
```

**Comment by mgerhardy** [comment]
6eb562583724da5315af6a8633ca2938214b5559 should fix this
